### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by yan12125** [termux/wcwidth#2]
Hello, I'd like to use this project in QTerminal, the terminal emulator for LXQT. (https://github.com/lxde/qtermwidget/pull/94) What's the license of `wcwidth.c`? Is it also MIT, like [wcwidth.py](https://github.com/jquast/wcwidth/blob/master/LICENSE.txt)?

**Comment by fornwall** [comment]
Right - I've added a LICENSE.txt file with the MIT license - let me know if there is anything else you need to improve.

**Comment by yan12125** [comment]
Thanks for the LICENSE declaration. Could you also add license headers to *.c and *.h files?

**Comment by fornwall** [comment]
I've added a small license preamble at https://github.com/termux/wcwidth/commit/d48cb1eca970f3d2971ae7cddfb375dc866ee714 - do you think that is enough?
